server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: mahdi
    password: "root"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    user: mahdi
    password: "root"